cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/logging/LoggingAspect.java, commons/commons-lang/src/main/java/com/clicktravel/common/security/ConfidentialString.java, commons/commons-lang/src/test/java/com/clicktravel/common/security/ConfidentialStringTest.java
Enable automatic logging against a pointcut. This is intended for uniform logging against all application API methods (command and query services) but could also be used for other layers.
Because potential confidential information is passed via the API, a simple string holder is also added, which does not display the string content in its toString() method. This is intended to hold strings passed to API methods like passwords and credit card numbers.
=> DP-91 Add logging aspect; Add string holder for confidential data

cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/filestore/FileItem.java
The current implementation of FileItem called getBytes when using the string based constructor. However this has different behaviour when on systems with different defaults e.g. Mac OS uses MacRoman.
Updates the constructor to assume UTF in all environments and adds utility for converting back to a string.
Signed-off-by: Robin Smith <robin.smith@clicktravel.com>
=> FileItem encoding was platform dependant

commons/commons-lang/src/main/java/com/clicktravel/common/hash/HashUtils.java
Do not depend on the default platform setting for character encoding when generating hashes.
=> FC-86 Hash generation should be platform independent

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/client/DocumentPropertyNamingStrategy.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/client/JsonDocumentSearchResponseUnmarshaller.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/client/JsonDocumentUpdateMarshaller.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/client/LowerCasePropertyNamingStrategy.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/CloudSearchEngineTest.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/client/JsonDocumentSearchResponseUnmarshallerTest.java
- Added Document property naming strategy to read all index names in lower case before unmarshalling to a document object.
- Set the naming strategy on the JSON document un/marshallers
- Updated tests to fix breakages
=> Added custom naming strategy to allow cloud search document to have camel case property names

cheddar/cheddar-rest/build.gradle, cheddar/cheddar-server/build.gradle, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java, commons/commons-httpclient/build.gradle
- Corrected version conflicts on various Jersey artifacts (was a mixture of 2.4 and 2.7) by upgrading to Jersey 2.15 throughout
- Updated to use Grizzly 2.3.16, which is pulled in by Jersey 2.15 Grizzly integration. Updated thread pool configuration, which differs in this newer Grizzly version.
These changes are in preparation to use Jersey Test.
=> DP-101 Use Jersey 2.15 and Grizzly 2.3.16

cheddar/cheddar-domain/src/main/java/com/clicktravel/cheddar/domain/feature/toggle/FeaturePropertyAdapter.java, cheddar/cheddar-domain/src/main/java/com/clicktravel/cheddar/domain/feature/toggle/FeatureRegistry.java
The FeatureRegistry uses a static state so it means that within the JVM it can only be initialised once. This caused a problem with reloading contexts again within the JVM as we need to within the Jersey Tests.
=> Allowed FeatureRegistry to be initialised many times with no side-effect

cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/AbstractEvent.java
When services that use Cheddar integrate on events the event code is sometimes shared to reduce duplication. When one of these events changes the other must also be built and redeployed because currently a 'UnrecognizedPropertyException' is thrown. The change in settings in this commit to the mapper will stop this behaviour from occurring reducing the coupling between services that integrate on events.
=> Set false to exception thrown when new event attributes are added to events

build.gradle
Cheddar's root build script has been updated to optionally run integration tests, like this:
gradle -DrunIntegrationTests checkAndUploadAll
Integration tests will run after unit tests but before uploading artifacts.
=> DP-95 Added build option to run AWS integration tests

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/QueryBuilder.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/StructuredQueryBuilderTest.java, cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/persistence/inmemory/document/search/mock/SearchParameter.java, cheddar/cheddar-integration-mocks/src/test/java/com/clicktravel/infrastructure/persistence/inmemory/document/search/mock/InMemoryMockDocumentSearchEngineTest.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/AndQuery.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/LuceneQuery.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/OrQuery.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/Query.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/RangeQuery.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/SimpleQuery.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/TermQuery.java, cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/LuceneQueryTest.java, cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/SimpleQueryTest.java, cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/query/StructuredQueryTest.java
In order to assert correctly on equality in Query subclasses, the equals method had to be implemented. The lack of these methods stopped mocks used during testing from working as intended. Refactoring to remove temporary code has also been added now that a more suitable implementation has been reached.
=> Added equals methods to Cloud Search Query subclasses

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sqs/SqsQueueResource.java
When the SQS queue resource was receiving a message from a queue if an amazon exception occurred it was only retrying if it was of type 'SERVICE'. This turns out to be insufficient as in practice if the host cannot be reached an IOException is thrown which results in a AmazonClientException. This change makes it so that any amazon exceptions result in a logged message and retry just as the requirements stated.
=> Removed server error only exception handling when failures occur while receiving messages

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDbTemplateIntegrationTest.java
Supplying a KeySetQuery to a fetch on a document store template will now support batch read. Pattern for retry unprocessed keys taken from AWS best practices.
Signed-off-by: Robin Smith <robin.smith@clicktravel.com>
=> Add support for batch read to DynamoDocumentStoreTemplate

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/AbstractDynamoDbTemplate.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDbTemplate.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplateTest.java
- Fixed a defect where version numbers were not being initialised and thereafter incremented when creating/updating document rows.
- Updating to add a version check to the update method to ensure correct versioning of data in Dynamo.
- Adding unit test
- Moved version constant to Abstract parent class for use by both children
@clicktravel-robin @clicktravel-basharat @clicktravel-tajinder @clicktravel-steffan - please review and merge if ok and we will do the framework bump.
=> [TRAV-192] increment version numbers when updating objects using doc API

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDbDataGenerator.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDbTemplateIntegrationTest.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDocumentStoreTemplateIntegrationTest.java
@clicktravel-tajinder @clicktravel-robin @clicktravel-basharat @clicktravel-steffan - noticed a couple of issues in the document template which are fixed by this pull request, please review and merge when happy.
1. Updating the fetch method for DynamoDocumentStoreTemplate so that if the field is indexed the index will be queried rather than a table scan being performed.
2. Fixed another bug with using comparators on numeric fields.
3. Added an integration test resulting in some refactoring of DynamoDbTemplateIntegrationTest to take out the DynamoDocumentStoreTemplate test and DynamoDbDataGenerator to be usable by both integration tests.
=> [TRAV-211] changing fetch to use indexes first

cheddar/cheddar-application/src/main/java/com/clicktravel/cheddar/application/security/SecurityChecker.java, cheddar/cheddar-application/src/test/java/com/clicktravel/cheddar/application/security/SecurityCheckerTest.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/AgentSecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/BasicSecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/SecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/SecurityContextHolder.java, cheddar/cheddar-context/src/test/java/com/clicktravel/cheddar/request/context/AgentSecurityContextTest.java, cheddar/cheddar-context/src/test/java/com/clicktravel/cheddar/request/context/BasicSecurityContextTest.java, cheddar/cheddar-context/src/test/java/com/clicktravel/cheddar/request/context/SecurityContextHolderTest.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityRequestFilter.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityResponseFilter.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityRequestFilterTest.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityResponseFilterTest.java
@ClickTravel/cheddarchapter
This is a *non-breaking* change as I have added deprecated methods to allow the previous ```getPrincipal()```, ```setPrincipal()``` and ```clearPrincipal()``` methods to work.
There is still some uncertainly (need discussion from API Chapter) over the choice of HTTP Headers to contain the principal/agent ids in the ```ContainerSecurityRequestFilter``` class, but the rest can still be reviewed.
=> [FC-91] Updated Cheddar to support Agents

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/status/RestAdapterStatusHolder.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/status/RestAdapterStatusRequestFilter.java
It is not clear why sometimes REST request counting goes wrong, making the count go below 0. If it should, log a (single) WARN rather than throw an exception which cannot be mapped correctly.
=> FC-92 Do not bring down app if REST request counting misbehaves

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/charset/CharsetResponseFilter.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/resource/status/StatusResource.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/charset/CharsetResponseFilterTest.java
```/status``` now returns ```application/json```
```/status/healthCheck``` now returns ```text/plain```
All endpoints have default ```charset=utf-8``` if ```Content-Type``` header is present in response
=> API-46 Fix Content-Type header in responses, including charset

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplateTest.java
Currently if you try to perform an attribute query on the has value, for example if you want to query hash without range it fails as it attempts to query an index table instead of the table itself.
This change checks that if the query name is the same as the PK because you can't have multiple keys with the same name then it will instead query the table directly. I have noticed an issue with index query around support for multiple keys but i will raise a separate bug report for that.
Signed-off-by: Robin Smith <robin.smith@clicktravel.com>
=> Support for hash key query

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/persistence/inmemory/database/InMemoryDatabaseTemplate.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/resource/status/StatusResource.java
Removing this unnecessary annotation gets rid of a WARN log message on application start
=> Remove empty path annotation on GET /status

commons/commons-httpclient/src/main/java/com/clicktravel/common/http/client/HttpClient.java
Some methods in HttpClient incorrectly use `MultivaluedHashMap` (a concrete class) rather than the general `MultivaluedMap` interface in their signatures.
=> Use MultivaluedMap (interface) instead of concrete class for method signatures

cheddar/cheddar-integration-aws/build.gradle, cheddar/cheddar-metrics/build.gradle, commons/commons-lang/build.gradle
Using Java 8 with older dependencies has issues concerning signed AWS requests.
=> DET-9 Update AWS SDK and Joda-Time dependencies

build.gradle, cheddar/cheddar-application/build.gradle, cheddar/cheddar-domain/build.gradle, cheddar/cheddar-events/build.gradle, cheddar/cheddar-integration-aws/build.gradle, cheddar/cheddar-integration-mocks/build.gradle, cheddar/cheddar-messaging/build.gradle, cheddar/cheddar-metrics-intercom/build.gradle, cheddar/cheddar-metrics/build.gradle, cheddar/cheddar-persisted-trackers/build.gradle, cheddar/cheddar-persistence/build.gradle, cheddar/cheddar-rest/build.gradle, cheddar/cheddar-server/build.gradle, cheddar/cheddar-system-events/build.gradle, cheddar/cheddar-tx-api/build.gradle, cheddar/cheddar-tx/build.gradle, commons/commons-httpclient/build.gradle, commons/commons-lang/build.gradle, commons/commons-test/build.gradle, logging-api.gradle, test.gradle
- Only SLF4J API and bridge dependencies are needed. The logging implementation choice should be left to the application.
- DRY test and logging dependencies
=> Trim logging dependencies to API only

commons/commons-test/src/main/java/com/clicktravel/common/test/BeanAssert.java
At the moment we cannot do BeanAssert on beans with Joda DateTime or LocalDate as they are final classes and cannot be mocked.
=> Added random DateTime and LocalDate to allow BeanAssert test

build.gradle, cheddar/cheddar-rest/build.gradle, cheddar/cheddar-server/build.gradle, commons/commons-httpclient/build.gradle, commons/commons-lang/build.gradle, gradle/wrapper/gradle-wrapper.properties
- Also removed cyclic dependency in commons-lang project
=> FC-102 Upgrade to Jersey 2.22.1 and Gradle 2.9

cheddar/cheddar-metrics/build.gradle, commons/commons-httpclient/build.gradle
Ensure no old versions of 'jackson-databind' (prior to 2.6.3) are present on any Eclipse project configurations. This works around an issue found in service testing in Eclipse where older versions of 'jackson-databind' are pulled in from certain sub-projects, rather than version 2.6.3 as specified in the top level project.
=> Workaround for Eclipse project dependency issues

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/AmazonCloudSearchDomainClientBuilder.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/CloudSearchEngine.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/manager/CloudSearchInfrastructureManager.java
- Currently all Cheddar applications using CloudSearch domain(s) will attempt to create the domain if it does not exist. This change enables the domain creation to be optionally skipped. Domain creation in Cheddar is performed by the class CloudSearchInfrastructureManager. Domain creation is now deprecated and in future this class will be removed.
- Added option to use default credentials provider chain when configuring CloudSearch client. This is intended to support use of IAM Roles when accessing AWS resources.
=> DP-161 Enable CloudSearch domain creation to be skipped

cheddar/cheddar-application/src/main/java/com/clicktravel/cheddar/application/pending/result/PendingResultOfferedEvent.java, cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/AbstractEvent.java, cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/EventMessageHandler.java, cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/EventPublisher.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sns/SnsTopicResource.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/exception/MessageHandlingException.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/ApplicationInstanceStartedEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/AppInstancesReadyToRunEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/NewAppInstancesBecomingHealthyEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/NewAppInstancesDeployedEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/OldAppInstancesEventProcessingHaltedEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/OldAppInstancesRestRequestsDrainedEvent.java, cheddar/cheddar-system-events/src/main/java/com/clicktravel/cheddar/system/event/application/lifecycle/OldAppInstancesTerminatedEvent.java
Events may contain confidential information which should not be casually logged. This commit changes logging of Events to use its toString() method, rather than logging the bodies of message used to publish them. This allows finer grained control of the logged content of published and handled events.
=> [FC-105] Log Event objects rather than messages

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/s3/S3FileStore.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/s3/S3FileStoreTest.java
After retriving an S3Object, we need to close this input stream as soon as possible, because the object contents aren't buffered in memory and stream directly from Amazon S3. Further, failure to close this stream can cause the request pool to become blocked.
=> [FC-107] S3ObjectInputStream should be closed after use

cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/cloudsearch/CloudSearchEngineTest.java, cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/database/exception/handler/PersistenceExceptionHandler.java, cheddar/cheddar-tx/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/database/tx/DatabaseAction.java
@clicktravel-steffan I think we can solve the problem of not matching the right persistence exception handler by adding a new method in `PersistenceExceptionHandler`. So that it won't contain braking changes, could be done in two steps:
1. Create the method `getExceptionClass` as `default` and client implementation so that the right exception class will be returned (ex. `ItemConstraintViolationException`)
2. Delete the default implementation of the method `getExceptionHandler` method
=> Improper persistence exception handling

gradle.properties
The version of Jackson used in Cheddar's combined dependencies is 2.6.6, not 2.6.3. This is due to a transitive dependency of cheddar-integration-aws.
=> Match version of Jackson used in transitive dependencies

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/persistence/inmemory/filestore/InMemoryInternetFileStore.java, cheddar/cheddar-integration-mocks/src/test/java/com/clicktravel/infrastructure/persistence/inmemory/filestore/InMemoryInternetFileStoreTest.java
This change is needed to model the behaviour existent in the
corresponding S3 implementation.
=> Fix for forming the file download URL based on the item's filename.

cheddar/cheddar-tx/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/database/tx/DatabaseAction.java, cheddar/cheddar-tx/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/database/tx/UpdateActionTest.java
If a collection of persistence exception handlers had been passed into the database action class a bug caused no action to be taken if an exception was thrown but did not match any of the handlers. The following code attempts to fix this bug by throwing the original persistence exception if no matching handler has been found and invoked.
=> Fixed silent failure of persistence error when no handler has been defined

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sqs/SqsBasicMessageQueue.java, cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sqs/SqsTypedMessageQueue.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/messaging/aws/sqs/SqsBasicMessageQueueTest.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/messaging/aws/sqs/SqsTypedMessageQueueTest.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/AbstractMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/InvalidBasicMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/InvalidMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/InvalidTypedMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/Message.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/SimpleBasicMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/SimpleMessage.java, cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/pooled/listener/PooledMessageListener.java, cheddar/cheddar-messaging/src/test/java/com/clicktravel/cheddar/infrastructure/messaging/InvalidBasicMessageTest.java, cheddar/cheddar-messaging/src/test/java/com/clicktravel/cheddar/infrastructure/messaging/InvalidTypedMessageTest.java, cheddar/cheddar-messaging/src/test/java/com/clicktravel/cheddar/infrastructure/messaging/SimpleBasicMessageTest.java, cheddar/cheddar-messaging/src/test/java/com/clicktravel/cheddar/infrastructure/messaging/SimpleMessageTest.java
- Attempt to delete SQS message up to 5 times, with requests 1500ms apart
- Add message ID to logged information when delete attempt fails
=> Change retry behaviour for deleting SQS messages

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/messaging/inmemory/InMemoryMessageVerifier.java, cheddar/cheddar-integration-mocks/src/test/java/com/clicktravel/infrastructure/messaging/inmemory/InMemoryMessageVerifierTest.java, cheddar/cheddar-integration-mocks/src/test/java/com/clicktravel/infrastructure/messaging/inmemory/StubOtherEvent.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java
This change adds a new test utility method 'InMemoryMessageVerifier#publishedEvents' for use in service tests. This method returns a list of Events that were published using an InMemoryMessagePublisher. The intention is to enable more flexible testing of published events, other than testing for complete equality with existing method 'InMemoryMessageVerifier#eventPublished'.
=> Add service test method for published events

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricCollector.java
This change adds a new method `MetricCollector#tagOrganisation` for marking an organisation with a tag.
=> Add metric-support for tagging organisations

cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonMappingExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonParseExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonProcessingExceptionMapperUtils.java
The registered Jersey feature `JacksonFeature` for converting JSON to/from Java objects, is also registering two standard mappers for the exceptions thrown during processing: `JsonParseExceptionMapper` and `JsonMappingExceptionMapper`. The problem is that these mappers are disclosing too many details, returning also the class names and part of the stack trace where the error occurred.
During investigating this issue, I found out that Jersey is working as follows when selecting the right mapper for an exception thrown:
- First it selects the mappers that are handling an exception that is the nearest in the class hierarchy from the actual thrown exception. 
- If there are many mappers meeting the previous requirement, then a mapper is selected based on its priority (the priority could be …
=> [FC-129] Add specific mappers for subclasses of JsonProcessingException to override the standard mappers provided by Jersey

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/persistence/inmemory/database/InMemoryDatabaseTemplate.java, cheddar/cheddar-integration-mocks/src/test/java/com/clicktravel/infrastructure/persistence/inmemory/database/InMemoryDatabaseTemplateTest.java
This update is to throw an exception consistent with the actual DynamoDB implementation when an item with a duplicate key is attempted to be saved via the `create` method.
=> Update InMemoryDatabaseTemplate behaviour in line with actual implementation

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplateTest.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/StubWithHashAndRangeAndGlobalSecondaryIndexItem.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDbDataGenerator.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/integration/DynamoDocumentStoreTemplateIntegrationTest.java
It was discovered that when the hash in a compound GSI was the same collumn as that of the tables hash then instead of querying using the range as well it ignored it and on queried on only the hash value. The fix was fairly benign but the testing was a little more complex but has seen to be working.
=> Fixed dynamodb fetch bug when dealing with compound GSI with hash the same as tables PK hash

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java, cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplateTest.java
An issue was found where data was being written to a compound GSI without the range part of the key.  This is something which DynamoDB allows but the Cheddar process of converting the item POJOs into JSON was including the null attributes explicitly mapped as null which is not allowed within Dynamo.  This fixes that issue by only writing properties to DynamoDB if they are not null.
=> Don't write null attributes when saving DynamoDB items

build.gradle, commons/commons-lang/build.gradle, gradle.properties, test.gradle
Powermock 1.6.3 has bad dependency metadata which required a workaround in Cheddar’s build script to change its transitive dependencies. Powermock 1.6.5 has corrected metadata, obsoleting the workaround.
=> Upgrade Powermock 1.6.3 -> 1.6.5

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java, cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUser.java
- Added setting and fetching by userId allowing users to actaully be gotten by Users.find()
- Added second simpler constructor for a metric user that will be used when a user is created without company id’s or custom attributes
- Updated unit tests to work with new way of finding
=> Fixed intercom metric collector to work with new company assigning

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomCustomAttributeToMetricCustomAttributeMapper.java, cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/MetricCustomAttributeToIntercomCustomAttributeMapper.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomCustomAttributeToMetricCustomAttributeMapperTest.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/MetricCustomAttributeToIntercomCustomAttributeMapperTest.java
`MetricUser` now contains Custom Attributes in a consistent non-intercom-dependent format when passed to / from `IntercomMetricCollector`, or updated directly with `addCustomAttributesToUser()`
=> [IAM-1667] IntercomMetricsAdaptor CustomAttributes API Issue

cheddar/cheddar-metrics/build.gradle, cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUser.java, cheddar/cheddar-metrics/src/test/java/com/clicktravel/cheddar/metrics/MetricUserTest.java
- In order to allow consumers to update the name and email address of user they have created in metrics systems, the MetricUser needs to allow the values to be mutated.  This will allow the consumer to call these update methods and then actually call the method to update the metric user in the metric system.
=> Provide support for updating the name and email address of a MetricUser

cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/DefaultSecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/NullSecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/SecurityContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/SecurityContextHolder.java, cheddar/cheddar-context/src/test/java/com/clicktravel/cheddar/request/context/DefaultSecurityContextTest.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityRequestFilter.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/security/ContainerSecurityRequestFilterTest.java
API-126 add support to cheddar to read the new app id header into the security context
=> API-126 add support to cheddar

cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/body/writer/ErrorResponseToTextPlainBodyWriter.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/ConstraintViolationExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/ContentMissingWebApplicationExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonMappingExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonParseExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/JsonProcessingExceptionMapper.java, cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/ValidationExceptionMapper.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/resource/config/RestResourceConfig.java
When an endpoint was registering two or more media types in the @Produces annotation, if any were none json such as text/plain, and an error was thrown the mapping was attempting to return a json like object and failing. A new message body writer has been written to allow the correct entity type to be written back in the response. The @Produces annotation has also been removed from the exception mappers which allows the current ‘Accept’ed media type to be passed through. This further enables responses of any json based media types regardless of any specific media type defined on the endpoint.
=> Add new message body writer to fix text/plain media type errors

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleController.java
We were finding that AWS long polling on certain resources such as message listeners needed 60 seconds instead of 50. Every so often an error was being thrown during deployment when shutdown occurred, stating that the thread had been killed while still processing. This should allow enough time for all threads to completed before the app is terminated.
=> Updated shutdown timeout in lifecycle controller to 65 seconds

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/flow/control/FlowControlledRequestFilter.java
Simple logging will allow apps built on cheddar to log out the performance of the configured rate limiting per rest request handled
=> Allow apps to turn on rest rate limit logging

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/random/data/RandomIntercomDataGenerator.java
When a user was being retreived from intercom its companies where being mapped to the id given by intercom and not the company id which is provided by the creator of the company. This fix should make sure that it is only known company_id’s that mapped back to a User when they are updated.
=> Fixed company id mix up bug in intercom metric controller

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/host/aws/ec2/Ec2InstanceDataAccessor.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationEC2InstanceTerminationRequestedEventHandler.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleController.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationEC2InstanceTerminationRequestedEventHandlerTest.java
This adds a new system event handler which responds to `ApplicationEC2InstanceTerminationRequestedEvent` by initiating the Java application to shut down. The intent is to use this event as part of AWS Auto Scaling Group scale-in operations, allowing graceful shutdown of the application before the EC2 instance is terminated.
=> Add system event handler to initiate application shutdown

cheddar/cheddar-server/build.gradle, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/logging/LoggingAspect.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/application/configuration/ApplicationConfigurationTest.java, cheddar/cheddar-server/src/test/resources/log4j.xml
This change adds logging of the principal id and team id for HTTP requests and responses to/from the server application.
=> Add context to log messages from LoggingAspect

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleController.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleControllerTest.java
This change adds an option `-Dworker.threads` to set the number of Grizzly worker threads. This defaults to 16.
=> Add option to set number of Grizzly worker threads

cheddar/cheddar-persisted-trackers/src/main/java/com/clicktravel/cheddar/application/tracker/PersistedTracker.java
- When a tracked process is started we see the "ProcessTracker started with id: <id>" message in the log.  However, on completion a log message which attempts to log the tracked process item out is written.  This doesn't contain a toString implementation so all we see is the object reference.  This change makes sure we see the "ProcessTracker ended with id: <id>" message to enable us to tie up the start and end of tracked processes.
=> Make "process tracker complete" log message consistent with the "process tracker started" log message

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleController.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java, cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/application/lifecycle/ApplicationLifecycleControllerTest.java
Status reports and health checks are to be served on the same port as other HTTP requests.
=> Remove distinct port for /status endpoints

cheddar/cheddar-server/build.gradle, gradle.properties
Also added the newest version of log4j in the test runtime dependacies to bring them uptodate with the services that now ue log4j 2.
=> Updated slf4j version to newest stable build

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java
- This allows API clients to handle errors as they wish rather than the underlying error being hidden by simply logging it out
=> Throw a MetricException if an error is encountered when trying to tag a company in Intercom

cheddar/cheddar-rest/build.gradle, commons/commons-json-provider/build.gradle, gradle.properties
JAX-RS API version 2.1 is the compile dependency of Jersey 2.27. This change just clarifies the selection of this version (rather than JAX-RS API version 2.0.1)
=> Clarify correct version of JAX-RS API is used

gradle.properties
`io.intercom:intercom-java:2.8.0` depends on a more recent version of Jackson. This change ensures a consistent version of Jackson is listed as a dependency of Cheddar (sub)projects.
=> Ensure consistent version of Jackson is used

cheddar/cheddar-domain/src/main/java/com/clicktravel/cheddar/domain/service/DomainServiceRegistry.java
An issue has been observed where `DomainService#getService` returned incorrect results shortly after the services were registered using `DomainService#init` on application startup, where these two methods are called on different threads. This change ensures initialisation is properly synchronised with lookups.
=> Ensure domain service lookup is thread safe

cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/EventMessageHandler.java, cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/EventPublisher.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/logging/LoggingAspect.java
In particular the amount of logging in th logging aspect has been removed to focus mainly on the dynamic data working under the assumption that the class name will be in the logging pattern making it clear this is a logging aspect log
The largest change is that the return call no longer logs the methodCallDetail as that is duplication of the details on the enter log, following on logs can be obtained by finding the enter log by thread id which is assumed to also be in your log pattern
=> Reduce fixed text in some logging

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/logging/LoggingAspect.java
Feedback has suggested that while the reduction of all input details is good that having at least the method name is helpful when debugging return values.
=> Adding back in method name to exit statement

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/resource/config/RestResourceConfig.java
During testing it was found that we no longer want to support automatically publishing a cheddar service’s documentation via swagger or application.wadl files that one may have had access to with the correct level of authentication.
=> Removed support for publishing Swagger and WADL files from cheddar services

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java
This change was turned off in this PR for the last round of pentest (https://github.com/travel-cloud/Cheddar/commit/bfd934a41fafb50b3b4cfe5b01b435266ff98c33). We still don’t want the wadl to be generated but this should allow us to easily get the newest swagger specifications for our core Grizzly/Java applications. The security issue will be fixed using infrastructure shortly.
=> Turned auto generated swagger back on for Grizzly apps

commons/commons-logging/build.gradle, commons/commons-logging/src/main/java/com/clicktravel/common/logging/JsonLog.java, commons/commons-logging/src/test/java/com/clicktravel/common/logging/JsonLogTest.java, settings.gradle
This change adds simple methods for logging messages as JSON rather than plain strings, using SLF4J and Jackson’s `ObjectMapper`.
=> Add utility methods for logging as JSON

cheddar/cheddar-context/build.gradle, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/AWSXraySegmentContext.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/AWSXraySegmentContextHolder.java, cheddar/cheddar-context/src/main/java/com/clicktravel/cheddar/request/context/DefaultAWSXraySegmentContext.java, cheddar/cheddar-integration-aws/build.gradle, cheddar/cheddar-server/build.gradle, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayRequestFilter.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayResponseFilter.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java
This adds AWS Xray support by manually creating a new segment on each request, storing it in local storage and closing as the response is returned to calling client.
When a segment is open and the AWS clients have been manually instrumented in the service you get output similar to that of what we see in the node projects.
If we are happy with this after letting it soak UAT with Wire (PR coming next) we can look into how to have this only turned on in production.
=> Added AWS XRay support to CHEDDAR

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayRequestFilter.java
This change adds a segment name building method that uses the request context to get the path with the templates unsubstitted so that we can name the XRay segments more genrically to allow for sample grouping.
=> Updated CHEDDAR XRay segment names to API request: {Method} {Path}

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayRequestFilter.java, cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayResponseFilter.java
This addition grabs any avilable User Agnet from the request headers and adds it to the segment. It also appends the response code and uses the number to set any throttling or faults to the segment to help with analysis.
=> [XRAY_WORK] Added Response data and User Agent to segments

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java, cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/random/data/RandomMetricDataGenerator.java, cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUser.java, cheddar/cheddar-metrics/src/test/java/com/clicktravel/cheddar/metrics/MetricUserTest.java
- We want to synchronise phone numbers in intercom with phone numbers in the platform
- The users service already uses the MetricUser and IntercomMetricCollector to synchronise data to Intercom so extend it to include the phone number
=> [CREW-6712] Update MetricUser to support phone number

commons/commons-lang/build.gradle, commons/commons-lang/src/main/java/com/clicktravel/common/security/ConfidentialString.java
- The object doesn't have a default constructor or public setter so was failing to be created from Json.
- The added Json attributes should ensure that it can be created from Json
=> [CREW-6852] - Ensure ConfidentialString can be built from Json

commons/commons-json-provider/src/main/java/com/clicktravel/common/http/application/ObjectMapperProvider.java
- Turning this on to avoid the choas the resulting InvalidFormatException causes when an unknown enum is read.
=> CREW-7414 Turn on reading unknown enums as null.

cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/URISyntaxExceptionMapper.java
- This will prevent URISyntaxExceptions from returning a full stack trace exposing internal details of the system
=> [CREW-8296] Add ExceptionMapper to catch URISyntaxException

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/query/QueryParameterValidationFilter.java
- Previously, when a query string such as q=" was appended to a URL, this caused a Grizzly error to be thrown which resulted in a HTML page with a stack trace.  This is not a good thing for security as it exposes frameworks and libraries that we use.
- This change adds a request filter which checks for the invalid query string and returns a HTTP 400 if it is invalid.
=> [CREW-8296] - Add request filter to Cheddar to return a structured error message if an invalid query string is appended to a URL

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/RestServer.java
- It looks like this is needed in order to not display the default error which contains the stack trace.
- The previous attempt to add a filter has not worked as it looks like the filters are at the Jersey server level which the processing for comes after the base Grizzly processing.
- The error being thrown is directly from Grizzly.
- Once I've tested and this does what we want, I may refine the error page.
=> [CREW-8296] - Add custom error page for Grizzly application to Cheddar
