cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/runtime/config/RuntimeConfiguration.java

"test" and "dev" are replacements for the existing "local" profile

DP-101 Add "test" and "dev" profiles

---

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/messaging/inmemory/InMemoryMessageForwardingControl.java
cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/messaging/inmemory/InMemoryMessageQueuePoller.java
cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/messaging/inmemory/InMemoryMessageSender.java

DP-107 Updated some Javadoc

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

DP-22 Upgrade to Gradle 2.3

---

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/AbstractDynamoDbTemplate.java
cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDbTemplate.java
cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java

@clicktravel-basharat @clicktravel-steffan @clicktravel-robin @clicktravel-tajinder 
please review, common code being moved to common superclass rather than duplicate

[TRAV-85] moving generate keys code to abstract super class

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java

FC-85 Add host identifier to log entries

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/runtime/config/PropertiesConfigurationBuilder.java

Locally modified properties file can have 'dev-' prefix. The 'local-' prefix is still accepted, but is now deprecated.
This (breaking) change also fixes a Spring Framework WARN on startup concerning PropertySourcesPlaceholderConfigurer.

DP-121 Allow locally modified properties file to have 'dev-' prefix

---

cheddar/cheddar-metrics/src/main/java/Metric.java
cheddar/cheddar-metrics/src/main/java/MetricCollector.java
cheddar/cheddar-metrics/src/main/java/MetricOrganisation.java
cheddar/cheddar-metrics/src/main/java/MetricUser.java

Signed-off-by: Tajinder Singh <tajinder.singh@clicktravel.com>

Added copyright headers

---

cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java

Signed-off-by: Chris Howell <chris.howell@clicktravel.com>

[hack] implementation of metric interface for intercom

---

cheddar/cheddar-metrics/build.gradle

Signed-off-by: Chris Howell <chris.howell@clicktravel.com>

[hack] Added Intercom dependency to gradle file

---

cheddar/cheddar-metrics/build.gradle

Signed-off-by: Chris Howell <chris.howell@clicktravel.com>

[hack] corrected dependency for intercom API

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java
cheddar/cheddar-metrics/build.gradle

Signed-off-by: Chris Howell <chris.howell@clicktravel.com>
@clicktravel-basharat can you have a look and let me know if it looks ok.

[hack] implement Event creation for Intercom metrics

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java

[hack] Added error logging to sendMetric method

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java

[hack] fail safe added if a metric is added of a non-supported type

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java
cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUser.java

Signed-off-by: Tajinder Singh <tajinder.singh@clicktravel.com>

Create user in Intercom

---

cheddar/cheddar-metrics-intercom/build.gradle

Signed-off-by: Tajinder Singh <tajinder.singh@clicktravel.com>

artefact missing

---

cheddar/cheddar-events/src/main/java/com/clicktravel/cheddar/event/EventMessageHandler.java
cheddar/cheddar-events/src/test/java/com/clicktravel/cheddar/event/EventMessageHandlerTest.java
cheddar/cheddar-events/src/test/java/com/clicktravel/cheddar/event/TestOtherConcreteEventHandler.java
commons/commons-lang/src/main/java/com/clicktravel/common/functional/StringUtils.java
commons/commons-lang/src/test/java/com/clicktravel/common/functional/StringUtilsTest.java

Also added string regex utility methods.

FC-94 Enable multiple handlers for same event type

---

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDbTemplate.java
cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/dynamodb/DynamoDocumentStoreTemplate.java

Log table scans at DEBUG level

---

commons/commons-lang/src/main/java/com/clicktravel/common/random/Randoms.java
commons/commons-lang/src/test/java/com/clicktravel/common/random/RandomsTest.java

This commit adds two new types of random data that can be generated:
* randomIntInRange - this will generate an int within a range that is inclusive of the from value and exclusive of the to value. Negative numbers are also supported with this method.
* randomCreditCardNumber - this will generate a random, valid, credit card number using the prefix provided. Supplying the prefix allows for differentiating between different provider types e.g. AMEX = 3, VISA = 4 etc.
@clicktravel-steffan please review and merge if happy.

[NON-JIRA] adding new random generation methods

---

config/checkstyle/suppressions.xml

Windows compatibility fix for Checkstyle config

---

cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/cdm1/SecurityConstraintViolationExceptionMapper.java

Updated SecurityContraintViolationExceptionMapper to include details of the security constraint being violated

Updated SecurityContraintViolationExceptionMapper

---

cheddar/cheddar-integration-mocks/src/main/java/com/clicktravel/infrastructure/persistence/inmemory/database/InMemoryDatabaseTemplate.java

@clicktravel-basharat Fixed LEQ and GEQ as they were the wrong way round.
Fixed issue when itemPropertyValue is null by changing the condition to values.equals(itemPropertyValue)
Signed-off-by: Chau Nguyen <chau.nguyen@clicktravel.com>

[FC-99] Fixed some executeQuery issues

---

cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/options/SearchOptions.java
cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/sort/SortOrder.java
cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/sort/SortingOption.java
cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/options/SearchOptionsTest.java
cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/sort/SortOrderTest.java
cheddar/cheddar-persistence/src/test/java/com/clicktravel/cheddar/infrastructure/persistence/document/search/sort/SortingOptionTest.java

Adding hashCode and equals methods. Please review and merge if happy.

[non-jira] implementing hashCode and equals to fix an issue with serice tests DocumentSearchEngine

---

build.gradle

DET-9 Upgrade to Java 8

---

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sqs/DefaultSqsQueueResourceFactory.java

Works fine when a new SQS queue is created, it subscribes to all SNS topics that it needs to.

NON-JIRA - Existing SQS queues are not subscribing to SNS topics.

---

build.gradle
cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/application/logging/LoggingAspect.java

Log advised method call entry in LoggingAspect

---

cheddar/cheddar-features/build.gradle
cheddar/cheddar-features/src/main/java/com/clicktravel/cheddar/features/AbsractFeatureService.java
cheddar/cheddar-features/src/main/java/com/clicktravel/cheddar/features/Feature.java
cheddar/cheddar-features/src/main/java/com/clicktravel/cheddar/features/FeaturesContext.java
cheddar/cheddar-features/src/main/java/com/clicktravel/cheddar/features/FeaturesContextHolder.java
cheddar/cheddar-features/src/test/java/com/clicktravel/cheddar/features/FeatureSetContextHolderTest.java
cheddar/cheddar-features/src/test/java/com/clicktravel/cheddar/features/FeatureSetContextTest.java
cheddar/cheddar-server/build.gradle
cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/features/ContainerFeatureSetRequestFilter.java
cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/features/ContainerFeatureSetResponseFilter.java
cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/features/ContainerFeatureSetRequestFilterTest.java
cheddar/cheddar-server/src/test/java/com/clicktravel/cheddar/server/http/filter/features/ContainerFeatureSetResponseFilterTest.java
settings.gradle

Moved the features code out of cheddar-context and duplicated from cheddar-domain to enable greater re-use

Added new project for features

---

cheddar/cheddar-persistence/src/main/java/com/clicktravel/cheddar/infrastructure/persistence/filestore/FileItem.java

Add constructor for FileItem

---

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/persistence/aws/s3/S3FileStore.java
cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/persistence/aws/s3/S3FileStoreTest.java

Set ContentDisposition filename parameter for downloads from S3FileStore

---

build.gradle
cheddar/cheddar-rest/build.gradle
cheddar/cheddar-server/build.gradle
cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/resource/config/RestResourceConfig.java
commons/commons-httpclient/build.gradle
commons/commons-httpclient/src/main/java/com/clicktravel/common/http/client/HttpClient.java
commons/commons-json-provider/build.gradle
commons/commons-json-provider/src/main/java/com/clicktravel/common/http/application/DecimalStringSerializer.java
commons/commons-json-provider/src/main/java/com/clicktravel/common/http/application/ObjectMapperProvider.java
gradle.properties
settings.gradle

Use Jackson as JSON provider in Jersey applications

---

cheddar/cheddar-cdm/build.gradle
config/checkstyle/suppressions.xml

Fix build script bug with codegen

---

cheddar/cheddar-application/build.gradle
cheddar/cheddar-application/src/test/java/com/clicktravel/cheddar/application/retry/RetryableAspectTest.java

- Added test runtime dependancy for exceptions not available at compile time.
- Added test class containing tests for all major happy path in the aspect.

Added unit tests for Retry Aspect

---

commons/commons-lang/src/main/java/com/clicktravel/common/functional/StringUtils.java
commons/commons-lang/src/test/java/com/clicktravel/common/functional/StringUtilsTest.java

- New utility method StringUtils#fromValue()
- Add missing unit tests for StringUtils class

Add utility method to get enum constant from String value

---

cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUser.java

Note to reviewer - please don't merge this.  If everything is fine, please add the 'in merge queue' tag and I'll merge when ready.

[IAM-920] - Added emailAddress to the MetricUser constructor so it is always set when creating users

---

cheddar/cheddar-cdm/build.gradle
cheddar/cheddar-cdm/codegen-config.json
commons/commons-json-provider/build.gradle
commons/commons-json-provider/src/main/java/com/clicktravel/common/http/application/ObjectMapperProvider.java
gradle/wrapper/gradle-wrapper.properties

Remove JAXB annotation processor from Jersey JSON provider

---

cheddar/cheddar-messaging/src/main/java/com/clicktravel/cheddar/infrastructure/messaging/pooled/listener/PooledMessageListener.java

Reduce log level for receive message error to WARN

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/rest/application/RestApplication.java

Workaround for shutdown issues with some applications

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java
cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java
cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricUserNotFoundException.java

This PR addresses the comments in https://github.com/travel-cloud/Cheddar/pull/207/files and also tidies up TODOs tests and adds additonal tests for conditions which did not have coverage.

Clean up reading user from Intercom.

---

commons/commons-lang/src/main/java/com/clicktravel/common/functional/StringUtils.java
commons/commons-lang/src/main/java/com/clicktravel/common/validation/Check.java
commons/commons-lang/src/test/java/com/clicktravel/common/functional/StringUtilsTest.java
commons/commons-lang/src/test/java/com/clicktravel/common/validation/CheckTest.java

Converts string to enum, wrapped inside the standard Check validation exceptions and error messaging behaviour.

[IAM-1869] string to enum validation method

---

gradle.properties

Bump to latest AWS SDK for Java version

---

cheddar/cheddar-integration-aws/build.gradle
cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/provisioning/aws/cloudformation/Stack.java
cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/provisioning/aws/cloudformation/StackTest.java

Basic query methods for AWS CloudFormation stacks

---

cheddar/cheddar-integration-aws/src/main/java/com/clicktravel/infrastructure/messaging/aws/sns/SnsTopicResource.java
cheddar/cheddar-integration-aws/src/test/java/com/clicktravel/infrastructure/messaging/aws/sns/SnsTopicResourceTest.java

for some reason type is not implied by using withStringValue so i’m setting it specifically.

Update SNS attribute to include type

---

cheddar/cheddar-metrics-intercom/src/main/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollector.java
cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/IntercomMetricCollectorTest.java
cheddar/cheddar-metrics-intercom/src/test/java/com/clicktravel/cheddar/metrics/intercom/random/data/RandomMetricDataGenerator.java
cheddar/cheddar-metrics/src/main/java/com/clicktravel/cheddar/metrics/MetricOrganisation.java

- Also includes some small refactoring to split the create/update company actions up to call the appropriate method on the Intercom API

Add mapping of remoteCreatedAt when creating an Intercom company

---

gradle.properties

This change is to enable use of S3 Select

Use latest AWS SDK for Java

---

commons/commons-lang/src/main/java/com/clicktravel/common/functional/CollectionUtils.java
commons/commons-lang/src/test/java/com/clicktravel/common/functional/CollectionUtilsTest.java

This is reduce the dependency on some transient depedencies pulled in by Cheddar e.g. jersey.repackaged.com.google.common.collect.Lists

Added methods to partition lists

---

cheddar/cheddar-server/build.gradle
gradle.properties

Upgraded Cheddar to use Jersey 2.27

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayRequestFilter.java
cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/aws/AWSXrayResponseFilter.java

These changes add:
- All Segments from a given service will be named after the service it originated from.
- Each Segment will not have HTTP path and method added as attributes to help with drilling down into individual requests traces.
- Xray can now be controlled by a environment property with comes from the Platform env properties and is set to default false to stop errors if it is unavailable.
- Added an extra check to see if the sample should be traced based on the current SamplingStrategy that the docs say should automatically call out to AWS console (https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling)
- Checks to see if a trace id is available and builds the segment with that if possible.

Updated XRay integration to support advanced features

---

commons/commons-lang/build.gradle
commons/commons-lang/src/main/java/com/clicktravel/common/security/Sanitiser.java
commons/commons-lang/src/test/java/com/clicktravel/common/security/SanitiserTest.java

- added unit test based on the tests in https://github.com/travel-cloud/ClickPlatform/blob/aa3471c32f8506353699c7417a2717804753e73f/projects/users/users-domain/src/test/java/com/clicktravel/services/users/domain/model/user/NameTest.java#L107

[CREW-7743] Adding Sanitiser for added security

---

commons/commons-lang/src/main/java/com/clicktravel/common/security/Sanitiser.java

- didn't know of the check against copyright comment needed on the class.

[CREW-7743] Fixing build

---

cheddar/cheddar-rest/src/main/java/com/clicktravel/cheddar/rest/exception/mapper/URISyntaxExceptionMapper.java

[CREW-8296] Add ExceptionMapper to catch URISyntaxException

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/query/QueryParameterValidationFilter.java

- The previous change hasn't worked so temporarily logging out the query string parameters to see what they are

[CREW-8296] - Add extra logging around query string parameters

---

cheddar/cheddar-server/src/main/java/com/clicktravel/cheddar/server/http/filter/query/QueryParameterValidationFilter.java

- This logging will be noisy and will be removed once the issue has been resolved

[CREW-8296] - Add more logging to help diagnose issue
